version: "3.7"

services:
  db:
    container_name: mysql
    build: 
      context: ./db
      dockerfile: Dockerfile
    platform: linux/amd64
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      # init.sql로 db 초기화
      - ./db/mysql-init-file:/docker-entrypoint-initdb.d/:ro
      - ./db/data:/var/lib/mysql
    networks:
      - app-tier
    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    restart: on-failure
    networks:
      - app-tier
    

networks:
  app-tier:
    driver: bridge
